
import os
import base64
from google.cloud import texttospeech
from google.oauth2 import service_account

# Initialize ElevenLabs client (new v1 API)
elevenlabs_client = None
try:
    from elevenlabs.client import ElevenLabs
    elevenlabs_api_key = os.environ.get("ELEVENLABS_API_KEY")
    if elevenlabs_api_key:
        elevenlabs_client = ElevenLabs(api_key=elevenlabs_api_key)
except Exception as e:
    print(f"ElevenLabs client initialization failed: {e}")

# Initialize Google Cloud TTS client
google_tts_client = None
try:
    credentials_path = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
    if credentials_path and os.path.exists(credentials_path):
        credentials = service_account.Credentials.from_service_account_file(credentials_path)
        google_tts_client = texttospeech.TextToSpeechClient(credentials=credentials)
    else:
        # Skip initialization; no credentials provided
        print("Google Cloud TTS: GOOGLE_APPLICATION_CREDENTIALS not set, skipping.")
except Exception as e:
    print(f"Google Cloud TTS client initialization failed: {e}")

def speak_text(text: str):
    audio_base64 = None
    error_message = ""

    # 1. Try ElevenLabs
    if elevenlabs_client:
        try:
            # Generate audio using the new v1 API
            audio_response = elevenlabs_client.text_to_speech.convert(
                text=text,
                voice_id="Rachel",
                model_id="eleven_multilingual_v2"
            )
            # audio_response is bytes
            audio_base64 = base64.b64encode(audio_response).decode('utf-8')
            return {
                "success": True,
                "provider": "ElevenLabs",
                "audio_base64": audio_base64,
                "message": "Audio generated successfully with ElevenLabs."
            }
        except Exception as e:
            error_message += f"ElevenLabs API error: {str(e)}. "
            print(f"ElevenLabs failed: {e}")

    # 2. Try Google Cloud Text-to-Speech as fallback
    if google_tts_client:
        try:
            synthesis_input = texttospeech.SynthesisInput(text=text)
            voice = texttospeech.VoiceSelectionParams(
                language_code="en-US",
                ssml_gender=texttospeech.SsmlVoiceGender.FEMALE
            )
            audio_config = texttospeech.AudioConfig(
                audio_encoding=texttospeech.AudioEncoding.MP3
            )
            response = google_tts_client.synthesize_speech(
                input=synthesis_input, voice=voice, audio_config=audio_config
            )
            audio_base64 = base64.b64encode(response.audio_content).decode('utf-8')
            return {
                "success": True,
                "provider": "GoogleCloudTTS",
                "audio_base64": audio_base64,
                "message": "Audio generated successfully with Google Cloud Text-to-Speech."
            }
        except Exception as e:
            error_message += f"Google Cloud TTS API error: {str(e)}. "
            print(f"Google Cloud TTS failed: {e}")
    
    return {"success": False, "error": error_message or "No TTS provider could generate audio."}

if __name__ == "__main__":
    test_text = "Hello, this is a test from Molly using her enhanced voice capabilities."
    result = speak_text(test_text)
    if result.get("success"):
        print(f"Audio generated by {result.get('provider')}. Base64 length:", len(result['audio_base64']))
    else:
        print("Error:", result.get("error"))
